# Generated by Django 4.2.6 on 2023-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=22, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
