# Generated by Django 4.2.6 on 2023-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('estetmepanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='user',
        ),
        migrations.AddField(
            model_name='panel',
            name='participants',
            field=models.ManyToManyField(to='account.profile'),
        ),
    ]
